export let items = [
    {id:1, title:"Šachy Havel", price:"300", url:"sachy-havel.jpg", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam id dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam egestas wisi a erat. Proin in tellus sit amet nibh dignissim sagittis. Nunc dapibus tortor vel mi dapibus sollicitudin. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Duis pulvinar. Aenean fermentum risus id tortor."},
    {id:2, title:"Hlava Havel", price:"89", url:"hlava-havel.jpg", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam id dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam egestas wisi a erat. Proin in tellus sit amet nibh dignissim sagittis. Nunc dapibus tortor vel mi dapibus sollicitudin. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Duis pulvinar. Aenean fermentum risus id tortor."},
    {id:3, title:"Kostky Havel", price:"11", url:"kostky-havel.png", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam id dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam egestas wisi a erat. Proin in tellus sit amet nibh dignissim sagittis. Nunc dapibus tortor vel mi dapibus sollicitudin. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Duis pulvinar. Aenean fermentum risus id tortor."},
    {id:4, title:"Hlava Halla", price:"90", url:"hlava-halla.png", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam id dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam egestas wisi a erat. Proin in tellus sit amet nibh dignissim sagittis. Nunc dapibus tortor vel mi dapibus sollicitudin. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Duis pulvinar. Aenean fermentum risus id tortor."},
    {id:5, title:"Nůž Halla", price:"87", url:"nuz-halla.png", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam id dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam egestas wisi a erat. Proin in tellus sit amet nibh dignissim sagittis. Nunc dapibus tortor vel mi dapibus sollicitudin. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Duis pulvinar. Aenean fermentum risus id tortor."},
    {id:6, title:"Hrubý Hlava", price:"21", url:"hruby-hlava.png", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam id dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam egestas wisi a erat. Proin in tellus sit amet nibh dignissim sagittis. Nunc dapibus tortor vel mi dapibus sollicitudin. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Duis pulvinar. Aenean fermentum risus id tortor."},
    {id:7, title:"Jakub Hlava", price:"771", url:"jakub-hlava.png", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam id dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam egestas wisi a erat. Proin in tellus sit amet nibh dignissim sagittis. Nunc dapibus tortor vel mi dapibus sollicitudin. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Duis pulvinar. Aenean fermentum risus id tortor."},
    {id:8, title:"Jakub Automat rofl", price:"67", url:"jakub-picovina.png", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam id dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam egestas wisi a erat. Proin in tellus sit amet nibh dignissim sagittis. Nunc dapibus tortor vel mi dapibus sollicitudin. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Duis pulvinar. Aenean fermentum risus id tortor."},
    {id:9, title:"Hruby Automat", price:"911", url:"hruby-automat.png", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam id dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam egestas wisi a erat. Proin in tellus sit amet nibh dignissim sagittis. Nunc dapibus tortor vel mi dapibus sollicitudin. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Duis pulvinar. Aenean fermentum risus id tortor."},
    {id:10, title:"Halla Kostky", price:"420", url:"halla-kostky.png", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam id dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam egestas wisi a erat. Proin in tellus sit amet nibh dignissim sagittis. Nunc dapibus tortor vel mi dapibus sollicitudin. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Duis pulvinar. Aenean fermentum risus id tortor."},
    {id:11, title:"Hrubý Postava", price:"69", url:"nekdo-drevo.png", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam id dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam egestas wisi a erat. Proin in tellus sit amet nibh dignissim sagittis. Nunc dapibus tortor vel mi dapibus sollicitudin. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Duis pulvinar. Aenean fermentum risus id tortor."},
    {id:12, title:"Jakub Loď", price:"18", url:"nekdo-lod.png", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam id dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam egestas wisi a erat. Proin in tellus sit amet nibh dignissim sagittis. Nunc dapibus tortor vel mi dapibus sollicitudin. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Duis pulvinar. Aenean fermentum risus id tortor."},
  ]